# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "Creating users..."
User.create(name: 'Jack', password: 'book', fav_genre: 'Fantasy', bio: 'A bibliophile who owns at least 7 copies of The Lord of the Rings')
User.create(name: 'Emily', password: 'book', fav_genre: 'Horror', bio: "Nursing student who doesn't even have the time to read")
User.create(name: 'Melissa', password: 'book', fav_genre: 'Adventure', bio: 'Manga all the way')
User.create(name: 'James', password: 'book', fav_genre: 'Western', bio: 'Rootin tootin cowboys yeehaw!')
User.create(name: 'Brandi', password: 'book', fav_genre: 'Romance', bio: 'I need more bookshelves')


puts "Creating books..."
Book.create(title: 'The Lord of the Rings', author: 'J. R. R. Tolkien', genre: 'Fantasy', length: 1197, pub_date: 'July 29, 1954', image: 'https://m.media-amazon.com/images/I/51bJhsl5VmL.jpg')
Book.create(title:'House of Leaves', author: 'Mark Z. Danielewski', genre: 'Horror', length: 738, pub_date: 'March 7, 2000', image: 'https://images-na.ssl-images-amazon.com/images/I/810pcXb+l3L.jpg')
Book.create(title:'The Sun Also Rises', author: 'Ernest Hemingway', genre: 'Romance', length: 320, pub_date: 'October 22, 1926', image: 'https://images-na.ssl-images-amazon.com/images/I/51cj37KTLRL._SX322_BO1,204,203,200_.jpg')
Book.create(title:'Leaves of Grass', author: 'Walt Whitman', genre: 'Poetry', length: 128, pub_date: 'July 4, 1855', image: 'https://images-na.ssl-images-amazon.com/images/I/71ZUAQQ-9IL.jpg')
Book.create(title:'Blood of Elves', author: 'Andrzej Sapkowski', genre: 'Fantasy', length: 285, pub_date: 'May 1, 2009', image: 'https://bookaudiobook.com/wp-content/uploads/2019/03/51DWHKXcFaL._SX293_BO1,204,203,200_.jpg')
Book.create(title:'Pride and Prejudice', author: 'Jane Austen', genre: 'Romance', length: 408, pub_date: 'January 28, 1813', image: 'https://m.media-amazon.com/images/I/51tiK-eB3JL.jpg')
Book.create(title:'Naruto, Vol. 1', author: 'Masashi Kishimoto', genre: 'Manga', length: 192, pub_date: 'March 1, 2000', image: 'https://images-na.ssl-images-amazon.com/images/I/51BucomQlHL._SX333_BO1,204,203,200_.jpg')
Book.create(title:'Demon Slayer: Kimetsu no Yaiba, Vol. 1', author: 'Koyoharu Gotouge', genre: 'Manga', length: 193, pub_date: 'June 3, 2016', image: 'https://images-na.ssl-images-amazon.com/images/I/81ZNkhqRvVL.jpg')
Book.create(title:'The Shining', author: 'Stephen King', genre: 'Horror', length: 447, pub_date: 'January 28, 1977', image: 'http://prodimage.images-bn.com/pimages/9780345806789_p0_v2_s1200x630.jpg')
Book.create(title:'A Game of Thrones', author: 'George R. R. Martin', genre: 'Fantasy', length: 968, pub_date: 'August 1, 1996', image: 'https://images-na.ssl-images-amazon.com/images/I/91dSMhdIzTL.jpg')
Book.create(title:'Bleach, Vol. 1', author: 'Tite Kubo', genre: 'Manga', length: 192, pub_date: 'January 1, 2006', image: 'https://images-na.ssl-images-amazon.com/images/I/81vbN16NtXL.jpg')
Book.create(title:'Lonesome Dove', author: 'Larry McMurtry', genre: 'Western', length: 866, pub_date: 'March 7, 1985', image: 'https://books.images.hpb.com/9780606351140/large.jpg')
Book.create(title:'Blood Meridian', author: 'Cormac McCarthy', genre: 'Western', length: 349, pub_date: 'April 2, 1985', image: 'https://images-na.ssl-images-amazon.com/images/I/71dbYRTINQL.jpg')
Book.create(title:'The Virginian', author: 'Owen Wister', genre: 'Western', length: 504, pub_date: 'December 7, 1902', image: 'https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781625581587/the-virginian-9781625581587_hr.jpg')
Book.create(title:'Frankenstein', author: 'Mary Shelley', genre: 'Horror', length: 280, pub_date: 'March 7, 1817', image: 'https://prodimage.images-bn.com/pimages/9798681827177_p0_v1_s550x406.jpg')
Book.create(title:'The Hobbit', author: 'J. R. R. Tolkien', genre: 'Fantasy', length: 318, pub_date: 'September 21, 1937', image: 'https://images-na.ssl-images-amazon.com/images/I/61aqO0sPF+L._SX329_BO1,204,203,200_.jpg')
Book.create(title:"A Connecticut Yankee in King Arthur's Court", author: 'Mark Twain', genre: 'Adventure', length: 528, pub_date: 'March 7, 1889', image: 'https://images-na.ssl-images-amazon.com/images/I/71Dp24QXhOL.jpg')
Book.create(title: "The Hitchhiker's Guide to the Galaxy", author: 'Douglas Adams', genre: 'Science Fiction', length: 208, pub_date: 'October 12, 1979', image: 'https://images-na.ssl-images-amazon.com/images/I/81XSN3hA5gL.jpg')
Book.create(title:'Dune', author: 'Frank Herbert', genre: 'Science Fiction', length: 722, pub_date: 'August 18, 1965', image: 'https://images-na.ssl-images-amazon.com/images/I/91Fq9Amx0pL.jpg')
Book.create(title:'Neuromancer', author: 'William Gibson', genre: 'Science Fiction', length: 292, pub_date: 'July 1, 1984', image: 'https://images-na.ssl-images-amazon.com/images/I/81N1TtCPxOL.jpg')
Book.create(title:'To Kill a Mockingbird', author: 'Harper Lee', genre: 'Adventure', length: 342, pub_date: 'July 11, 1960', image: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553383690l/2657.jpg')
Book.create(title:'Anna Karenina', author: 'Leo Tolstoy', genre: 'Romance', length: 864, pub_date: 'March 7, 1877', image: 'https://images-na.ssl-images-amazon.com/images/I/41ebi9z2DjL.jpg')
Book.create(title:'The Tale of Genji', author: 'Murasaki Shikibu', genre: 'Romance', length: 1300, pub_date: '1008', image: 'https://m.media-amazon.com/images/I/61YCVIKjlSL.jpg')
Book.create(title:'Moby Dick', author: 'Herman Melville', genre: 'Adventure', length: 378, pub_date: 'October 18, 1851', image: 'https://images-na.ssl-images-amazon.com/images/I/41VnFKC9srL.jpg')
Book.create(title:'One Hundred Years of Solitude', author: 'Gabriel García Márquez', genre: 'Fantasy', length: 433, pub_date: 'March 7, 1967', image: 'https://images-na.ssl-images-amazon.com/images/I/91mftQtgAkL.jpg')

puts "Creating shelves..."
Shelf.create(user_id: 1, book_id: 1)
Shelf.create(user_id: 1, book_id: 2)
Shelf.create(user_id: 1, book_id: 12)
Shelf.create(user_id: 1, book_id: 15)
Shelf.create(user_id: 1, book_id: 16)
Shelf.create(user_id: 1, book_id: 21)
Shelf.create(user_id: 1, book_id: 23)
Shelf.create(user_id: 1, book_id: 25)
Shelf.create(user_id: 3, book_id: 7)
Shelf.create(user_id: 3, book_id: 8)
Shelf.create(user_id: 3, book_id: 11)
Shelf.create(user_id: 4, book_id: 12)
Shelf.create(user_id: 4, book_id: 13)
Shelf.create(user_id: 4, book_id: 14)
Shelf.create(user_id: 4, book_id: 17)
Shelf.create(user_id: 5, book_id: 3)
Shelf.create(user_id: 5, book_id: 6)
Shelf.create(user_id: 5, book_id: 22)
Shelf.create(user_id: 5, book_id: 23)



puts "Creating reviews..."
Review.create(book_id: 1, content: 'Came for the dwarf but stayed for the prose')
Review.create(book_id: 1, content: 'Best book ever')
Review.create(book_id: 1, content: 'We all need a Sam')
Review.create(book_id: 2, content: "I didn't understand any of it. Absolutely amazing.")
Review.create(book_id: 7, content: "Ninjas are cool")
Review.create(book_id: 7, content: "Had to start reading when I finished the anime")
Review.create(book_id: 12, content: "The pigs were the best part. I cried a lot.")
Review.create(book_id: 15, content: "It's just letters?")
Review.create(book_id: 15, content: "A masterpiece of literature")
Review.create(book_id: 2, content: "It physically hurt to read this")
Review.create(book_id: 3, content: "Decent")
Review.create(book_id: 4, content: "Couldn't put it down")
Review.create(book_id: 5, content: "My new favorite")
Review.create(book_id: 10, content: "Contrite garbage")
Review.create(book_id: 12, content: "WOOOOO")
Review.create(book_id: 17, content: "The movie was better")
Review.create(book_id: 18, content: "Can't wait for the sequel")
Review.create(book_id: 19, content: "Captivating")
Review.create(book_id: 19, content: "Was it written by a child?")
Review.create(book_id: 20, content: "Really good kindling, not so great book")
Review.create(book_id: 21, content: "Wonderful")
Review.create(book_id: 22, content: "Changed my life")
Review.create(book_id: 23, content: "I've read it 20 times")
Review.create(book_id: 24, content: "A solid work")
Review.create(book_id: 25, content: "Bit of a let down but the author is new so what can you expect")


puts "Creating ratings..."
Rating.create(book_id: 1, rating: 10)
Rating.create(book_id: 1, rating: 10)
Rating.create(book_id: 1, rating: 10)
Rating.create(book_id: 2, rating: 7)
Rating.create(book_id: 7, rating: 8)
Rating.create(book_id: 7, rating: 6)
Rating.create(book_id: 12, rating: 9)
Rating.create(book_id: 15, rating: 4)
Rating.create(book_id: 15, rating: 10)
Rating.create(book_id: 2, rating: 1)
Rating.create(book_id: 3, rating: 5)
Rating.create(book_id: 4, rating: 8)
Rating.create(book_id: 5, rating: 6)
Rating.create(book_id: 10, rating: 2)
Rating.create(book_id: 12, rating: 10)
Rating.create(book_id: 17, rating: 5)
Rating.create(book_id: 18, rating: 8)
Rating.create(book_id: 19, rating: 7)
Rating.create(book_id: 19, rating: 4)
Rating.create(book_id: 20, rating: 3)
Rating.create(book_id: 21, rating: 9)
Rating.create(book_id: 22, rating: 10)
Rating.create(book_id: 23, rating: 10)
Rating.create(book_id: 24, rating: 8)
Rating.create(book_id: 25, rating: 6)